include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_null_checks_in_equality_operators
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - invalid_case_patterns
    - missing_whitespace_between_adjacent_strings
    - noop_primitive_operations
    - omit_obvious_local_variable_types
    - prefer_const_declarations
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_async
    - unnecessary_await_in_return
