targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: lib/infra/api/graphql/**{.graphql,.gql,.graphqls}
          scopes:
            - lib/infra/api/graphql/**{.graphql,.gql,.graphqls}
          outputDirectory: gen
          generatedFileHeader: "// ignore_for_file: type=lint\n"
          scalars:
            AWSDateTime:
              type: DateTime
              fromJsonFunctionName: fromGraphQLAWSDateTime
              toJsonFunctionName: toGraphQLAWSDateTime
              import: "package:todo/infra/api/graphql/scalars.dart"
